# Generated by Django 5.1.1 on 2024-11-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
