# Generated by Django 5.1.1 on 2024-11-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_membershipplan_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='icon_color',
            field=models.CharField(default='#000', help_text="Enter a valid color (e.g., '#FF0000' or 'red')", max_length=20),
        ),
    ]
